export type RideBand = '骑行 5 分钟内' | '骑行 10 分钟内' | '骑行 15 分钟内';
export type TimeFilter = '早餐' | '午饭' | '下午加餐' | '晚饭' | '夜宵';
export type SceneFilter = '快点吃饱' | '本地味道' | '一个人方便' | '两三人一起' | '便宜不踩雷' | '晚点也能吃';
export type VerificationStatus = 'verified' | 'needs-confirmation';

export interface WowoRestaurant {
    id: string;
    no: string;
    category: '早餐类' | '小吃类' | '夜宵类' | '中晚餐';
    shortName: string;
    fullName: string;
    dish: string;
    address: string;
    rideMinutes: number;
    rideBand: RideBand;
    sourceBand: RideBand;
    times: TimeFilter[];
    scenes: SceneFilter[];
    baseRating: number;
    baseVotes: number;
    seedNotes: string[];
    mapKeyword: string;
    amapName: string;
    amapAddress: string;
    amapLink?: string;
    amapPoiId?: string;
    amapLocation?: string;
    verificationStatus: VerificationStatus;
}

export interface PendingAmapRestaurant {
    name: string;
    sourceBand: RideBand;
    category: string;
    reason: string;
    suggestedKeyword: string;
}

export interface WowoSeedNote {
    id: string;
    shopName: string;
    text: string;
    createdAt: number;
}

export const timeFilters: TimeFilter[] = ['早餐', '午饭', '下午加餐', '晚饭', '夜宵'];
export const sceneFilters: SceneFilter[] = [
    '快点吃饱',
    '本地味道',
    '一个人方便',
    '两三人一起',
    '便宜不踩雷',
    '晚点也能吃',
];

export const rideBands: RideBand[] = ['骑行 5 分钟内', '骑行 10 分钟内', '骑行 15 分钟内'];

export const rideBandMax: Record<RideBand, number> = {
    '骑行 5 分钟内': 5,
    '骑行 10 分钟内': 10,
    '骑行 15 分钟内': 15,
};

export const wowoRestaurants: WowoRestaurant[] = [
    {
        id: 'R05-01',
        no: 'A03',
        category: '早餐类',
        shortName: '老蔡猪肝大王',
        fullName: '老蔡猪肝大王',
        dish: '猪肝汤粉',
        address: '南昌市西湖区桃苑中路外国语学校对面',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.6,
        baseVotes: 16,
        seedNotes: ['想吃本地粉汤又不想走太远，可以先看这家。', '猪肝汤粉适合早上垫一碗。', '一个人吃也很方便。'],
        mapKeyword: '老蔡猪肝大王 桃苑中路 外国语学校对面',
        amapName: '老蔡猪肝大王',
        amapAddress: '南昌市西湖区桃苑中路外国语学校对面',
        amapPoiId: 'B0HKB1I589',
        amapLocation: '115.886694,28.650351',
        verificationStatus: 'needs-confirmation',
    },
    {
        id: 'R10-01',
        no: 'A10',
        category: '早餐类',
        shortName: '秦胖子肉陀',
        fullName: '秦胖子肉陀良心店',
        dish: '粉面汤',
        address: '南昌市西湖区石头街108号',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.7,
        baseVotes: 18,
        seedNotes: [
            '大士院一带想吃粉面汤，可以作为稳妥候选。',
            '早上或中午都能凑一顿。',
            '适合第一次来南昌试本地粉汤。',
        ],
        mapKeyword: '秦胖子肉陀良心店 石头街108号',
        amapName: '秦胖子肉陀良心店',
        amapAddress: '南昌市西湖区石头街108号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031703WP3&name=%E7%A7%A6%E8%83%96%E5%AD%90%E8%82%89%E9%99%80%E8%89%AF%E5%BF%83%E5%BA%97',
        amapPoiId: 'B031703WP3',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-02',
        no: 'B10',
        category: '小吃类',
        shortName: '小欧水煮',
        fullName: '小欧水煮店(会堂路店)',
        dish: '水煮',
        address: '南昌市西湖区会堂东路45号住宅小区10栋',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['下午加餐', '晚饭', '夜宵'],
        scenes: ['本地味道', '一个人方便', '便宜不踩雷', '晚点也能吃'],
        baseRating: 4.5,
        baseVotes: 14,
        seedNotes: ['下午想吃点重口小吃，可以看看水煮。', '一人加餐也方便。', '晚上回来想补一口也适合。'],
        mapKeyword: '小欧水煮店 会堂路店 会堂东路45号住宅小区10栋',
        amapName: '小欧水煮店(会堂路店)',
        amapAddress: '南昌市西湖区会堂东路45号住宅小区10栋',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031705BFI&name=%E5%B0%8F%E6%AC%A7%E6%B0%B4%E7%85%AE%E5%BA%97%28%E4%BC%9A%E5%A0%82%E8%B7%AF%E5%BA%97%29',
        amapPoiId: 'B031705BFI',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-03',
        no: 'B11',
        category: '小吃类',
        shortName: '小邓臭豆腐',
        fullName: '万寿宫小邓臭豆腐',
        dish: '臭豆腐',
        address: '南昌市西湖区中山路420号万寿宫',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['下午加餐', '晚饭', '夜宵'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷', '晚点也能吃'],
        baseRating: 4.8,
        baseVotes: 23,
        seedNotes: ['想快速吃一点南昌小吃，可以先看臭豆腐。', '边走边吃很合适。', '适合下午或夜里加餐。'],
        mapKeyword: '万寿宫小邓臭豆腐 中山路420号万寿宫',
        amapName: '万寿宫小邓臭豆腐',
        amapAddress: '南昌市西湖区中山路420号万寿宫(八一馆地铁站5号口步行250米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0LKM55NUW&name=%E4%B8%87%E5%AF%BF%E5%AE%AB%E5%B0%8F%E9%82%93%E8%87%AD%E8%B1%86%E8%85%90',
        amapPoiId: 'B0LKM55NUW',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-04',
        no: 'B03',
        category: '小吃类',
        shortName: '香辣水煮',
        fullName: '香辣水煮(船山路)',
        dish: '水煮',
        address: '南昌市西湖区船山路217号',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['晚饭', '夜宵'],
        scenes: ['本地味道', '一个人方便', '两三人一起', '晚点也能吃'],
        baseRating: 4.3,
        baseVotes: 12,
        seedNotes: ['能吃辣再考虑，适合想来点刺激的。', '夜里口味重一点可以选。', '不太能吃辣要谨慎。'],
        mapKeyword: '香辣水煮 船山路217号',
        amapName: '香辣水煮',
        amapAddress: '南昌市西湖区船山路217号',
        amapPoiId: 'B03870G61U',
        amapLocation: '115.891511,28.652054',
        verificationStatus: 'needs-confirmation',
    },
    {
        id: 'R15-01',
        no: 'A15',
        category: '早餐类',
        shortName: '小罗子汤店',
        fullName: '小罗子汤店(大士院总店)',
        dish: '粉面汤',
        address: '南昌市东湖区大士院南区23栋',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.8,
        baseVotes: 28,
        seedNotes: [
            '大士院片区的粉面汤代表，适合愿意骑远一点的时候。',
            '早餐想吃本地味可以看它。',
            '人多时可能需要排一会儿。',
        ],
        mapKeyword: '小罗子汤店 大士院总店 大士院南区23栋',
        amapName: '小罗子汤店(大士院总店)',
        amapAddress: '南昌市东湖区大士院南区23栋',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFFMI84L&name=%E5%B0%8F%E7%BD%97%E5%AD%90%E6%B1%A4%E5%BA%97%28%E5%A4%A7%E5%A3%AB%E9%99%A2%E6%80%BB%E5%BA%97%29',
        amapPoiId: 'B0FFFMI84L',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-02',
        no: 'A16',
        category: '早餐类',
        shortName: '春洪猪血店',
        fullName: '春洪猪血店',
        dish: '猪血粉',
        address: '南昌市东湖区包家巷89号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.4,
        baseVotes: 15,
        seedNotes: ['猪血粉爱好者可以放进备选。', '适合早餐或中午吃一碗。', '口味偏本地，外地住客可尝鲜。'],
        mapKeyword: '春洪猪血店 包家巷89号',
        amapName: '春洪猪血店',
        amapAddress: '南昌市东湖区包家巷89号',
        amapPoiId: 'B0FFFQUF4L',
        amapLocation: '115.889211,28.683604',
        verificationStatus: 'needs-confirmation',
    },
    {
        id: 'R15-03',
        no: 'B15',
        category: '小吃类',
        shortName: '杨大娘粽子',
        fullName: '杨大娘粽子',
        dish: '粽子',
        address: '南昌市东湖区棉花街南昌八一起义纪念馆北侧约30米',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '下午加餐'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.7,
        baseVotes: 20,
        seedNotes: ['想吃小吃又不想坐下来太久，可以买个粽子。', '适合边逛边吃。', '早餐或下午加餐都可以。'],
        mapKeyword: '杨大娘粽子 棉花街',
        amapName: '杨大娘粽子',
        amapAddress: '南昌市东湖区棉花街南昌八一起义纪念馆北侧约30米',
        amapPoiId: 'B0FFFPY63W',
        amapLocation: '115.894390,28.675664',
        verificationStatus: 'needs-confirmation',
    },
    {
        id: 'R15-04',
        no: 'B16',
        category: '小吃类',
        shortName: '细英水酒店',
        fullName: '细英水酒店(大士院住宅店)',
        dish: '米酒',
        address: '南昌市东湖区大士院住宅三区8号楼9栋对面',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['下午加餐', '晚饭'],
        scenes: ['本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 13,
        seedNotes: ['想尝一点本地米酒小吃，可以看这家。', '适合轻松加餐。', '不想吃太正式正餐时可以选。'],
        mapKeyword: '细英水酒店 大士院住宅店 大士院住宅三区8号楼9栋对面',
        amapName: '细英水酒店(大士院住宅店)',
        amapAddress: '南昌市东湖区大士院住宅三区8号楼9栋对面',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0JG1UANTL&name=%E7%BB%86%E8%8B%B1%E6%B0%B4%E9%85%92%E5%BA%97%28%E5%A4%A7%E5%A3%AB%E9%99%A2%E4%BD%8F%E5%AE%85%E5%BA%97%29',
        amapPoiId: 'B0JG1UANTL',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-05',
        no: 'B17',
        category: '小吃类',
        shortName: '陈记绿豆糕',
        fullName: '陈记手工绿豆饼(珠宝街店)',
        dish: '绿豆糕',
        address: '南昌市东湖区珠宝街97号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['下午加餐'],
        scenes: ['本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.6,
        baseVotes: 14,
        seedNotes: ['下午想吃甜口小点，可以顺手带一份。', '适合买了慢慢吃。', '不想吃正餐时很轻。'],
        mapKeyword: '陈记手工绿豆饼 珠宝街店',
        amapName: '陈记手工绿豆饼(珠宝街店)',
        amapAddress: '南昌市东湖区珠宝街97号',
        amapPoiId: 'B0FFM7KMC3',
        amapLocation: '115.895381,28.674309',
        verificationStatus: 'needs-confirmation',
    },
    {
        id: 'R10-05',
        no: 'A11',
        category: '早餐类',
        shortName: '良友小吃',
        fullName: '良友小吃(绿源小区店)',
        dish: '小肉包、汤粉',
        address: '南昌市西湖区团结路88号',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.7,
        baseVotes: 20,
        seedNotes: ['一元小肉包很适合早餐先垫一口。', '汤粉和包子一起点更稳。', '早上想吃本地老店可以看这家。'],
        mapKeyword: '良友小吃 绿源小区店 团结路88号',
        amapName: '良友小吃(绿源小区店)',
        amapAddress: '南昌市西湖区团结路88号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFKPDNWB&name=%E8%89%AF%E5%8F%8B%E5%B0%8F%E5%90%83%28%E7%BB%BF%E6%BA%90%E5%B0%8F%E5%8C%BA%E5%BA%97%29',
        amapPoiId: 'B0FFKPDNWB',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-06',
        no: 'D10',
        category: '夜宵类',
        shortName: '英姐小吃',
        fullName: '英姐小吃(系马桩总店)',
        dish: '水煮',
        address: '南昌市西湖区系马桩街137-1号',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['下午加餐', '晚饭', '夜宵'],
        scenes: ['本地味道', '一个人方便', '两三人一起', '便宜不踩雷', '晚点也能吃'],
        baseRating: 4.6,
        baseVotes: 27,
        seedNotes: ['想吃南昌水煮可以把它放进候选。', '晚上结伴吃会更有气氛。', '营业到比较晚，适合夜里补一顿。'],
        mapKeyword: '英姐小吃 系马桩总店 系马桩街137-1号',
        amapName: '英姐小吃(系马桩总店)',
        amapAddress: '南昌市西湖区系马桩街137-1号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031703JGD&name=%E8%8B%B1%E5%A7%90%E5%B0%8F%E5%90%83%28%E7%B3%BB%E9%A9%AC%E6%A1%A9%E6%80%BB%E5%BA%97%29',
        amapPoiId: 'B031703JGD',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-07',
        no: 'C10',
        category: '中晚餐',
        shortName: '鄱湖岛饭庄',
        fullName: '鄱湖岛饭庄(朝阳洲中路老店)',
        dish: '鳜鱼煮粉、赣菜',
        address: '南昌市西湖区朝阳中路269号',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起'],
        baseRating: 4.5,
        baseVotes: 14,
        seedNotes: ['想吃更正式一点的本地菜可以看它。', '两三个人点菜更合适。', '价格不算低，适合认真吃一顿。'],
        mapKeyword: '鄱湖岛饭庄 朝阳洲中路老店 朝阳中路269号',
        amapName: '鄱湖岛饭庄(朝阳洲中路老店)',
        amapAddress: '南昌市西湖区朝阳中路269号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031703MS5&name=%E9%84%B1%E6%B9%96%E5%B2%9B%E9%A5%AD%E5%BA%84%28%E6%9C%9D%E9%98%B3%E6%B4%B2%E4%B8%AD%E8%B7%AF%E8%80%81%E5%BA%97%29',
        amapPoiId: 'B031703MS5',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-06',
        no: 'A17',
        category: '早餐类',
        shortName: '黄记瓦罐汤',
        fullName: '黄记瓦罐煨汤(广场东路店)',
        dish: '瓦罐汤、拌粉',
        address: '南昌市西湖区广场东路119号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '午饭', '晚饭', '夜宵'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷', '晚点也能吃'],
        baseRating: 4.6,
        baseVotes: 146,
        seedNotes: ['瓦罐汤加拌粉是很南昌的一套。', '一个人吃饭也比较顺手。', '晚点想喝口热汤也能看它。'],
        mapKeyword: '黄记瓦罐煨汤 广场东路店 广场东路119号',
        amapName: '黄记瓦罐煨汤(广场东路店)',
        amapAddress: '南昌市西湖区广场东路119号(丁公路北地铁站7号口步行430米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031705CLR&name=%E9%BB%84%E8%AE%B0%E7%93%A6%E7%BD%90%E7%85%A8%E6%B1%A4%28%E5%B9%BF%E5%9C%BA%E4%B8%9C%E8%B7%AF%E5%BA%97%29',
        amapPoiId: 'B031705CLR',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-07',
        no: 'B18',
        category: '小吃类',
        shortName: '胖子水煮',
        fullName: '胖子水煮店(无任何分店)',
        dish: '水煮',
        address: '南昌市西湖区火车站铁路三村14栋5单元',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['午饭', '下午加餐', '晚饭'],
        scenes: ['本地味道', '一个人方便', '两三人一起', '便宜不踩雷'],
        baseRating: 4.6,
        baseVotes: 187,
        seedNotes: ['水煮爱好者可以把它作为稍远备选。', '适合下午或晚饭吃点重口。', '人多时可能需要排队。'],
        mapKeyword: '胖子水煮店 无任何分店 火车站铁路三村14栋5单元',
        amapName: '胖子水煮店(无任何分店)',
        amapAddress: '南昌市西湖区火车站铁路三村14栋5单元',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFFF8YHI&name=%E8%83%96%E5%AD%90%E6%B0%B4%E7%85%AE%E5%BA%97%28%E6%97%A0%E4%BB%BB%E4%BD%95%E5%88%86%E5%BA%97%29',
        amapPoiId: 'B0FFFF8YHI',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-08',
        no: 'B19',
        category: '小吃类',
        shortName: '小敖臭豆腐',
        fullName: '小敖臭豆腐',
        dish: '臭豆腐',
        address: '南昌市西湖区棉花街119号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['下午加餐', '晚饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 15,
        seedNotes: ['万寿宫附近想吃臭豆腐可以看这家。', '适合边逛边吃。', '从高德补全地址为棉花街119号。'],
        mapKeyword: '小敖臭豆腐 棉花街119号',
        amapName: '小敖臭豆腐',
        amapAddress: '南昌市西湖区棉花街119号(万寿宫地铁站2号口步行390米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFKX40OB&name=%E5%B0%8F%E6%95%96%E8%87%AD%E8%B1%86%E8%85%90',
        amapPoiId: 'B0FFKX40OB',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-09',
        no: 'A18',
        category: '早餐类',
        shortName: '眼镜子煎包',
        fullName: '老字号眼镜子煎包汤包店',
        dish: '煎包、汤包',
        address: '南昌市东湖区包家巷42号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 19,
        seedNotes: ['早上想吃煎包汤包可以看这家。', '藏在巷子里的本地小店。', '高德核准地址显示为包家巷42号。'],
        mapKeyword: '老字号眼镜子煎包汤包店 包家巷42号',
        amapName: '老字号眼镜子煎包汤包店',
        amapAddress: '南昌市东湖区包家巷42号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0317040EO&name=%E8%80%81%E5%AD%97%E5%8F%B7%E7%9C%BC%E9%95%9C%E5%AD%90%E7%85%8E%E5%8C%85%E6%B1%A4%E5%8C%85%E5%BA%97',
        amapPoiId: 'B0317040EO',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-10',
        no: 'B20',
        category: '小吃类',
        shortName: '缘夫妻切糕',
        fullName: '缘夫妻切糕店',
        dish: '切糕',
        address: '南昌市西湖区西上谕亭街14号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['下午加餐'],
        scenes: ['本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.4,
        baseVotes: 8,
        seedNotes: ['想吃甜口小吃可以看这家。', '适合下午顺路带一份。', '不想吃正餐时比较轻。'],
        mapKeyword: '缘夫妻切糕店 西上谕亭街14号',
        amapName: '缘夫妻切糕店',
        amapAddress: '南昌市西湖区西上谕亭街14号(八一馆地铁站1号口步行240米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0KK2G21SV&name=%E7%BC%98%E5%A4%AB%E5%A6%BB%E5%88%87%E7%B3%95%E5%BA%97',
        amapPoiId: 'B0KK2G21SV',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-11',
        no: 'D15',
        category: '夜宵类',
        shortName: '徐军老汤店',
        fullName: '徐军老汤店',
        dish: '老汤、炒粉',
        address: '南昌市东湖区金家山社区西南门旁',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['晚饭', '夜宵'],
        scenes: ['本地味道', '一个人方便', '两三人一起', '晚点也能吃'],
        baseRating: 4.5,
        baseVotes: 24,
        seedNotes: ['晚上想喝口热汤可以看它。', '营业到比较晚，适合夜宵。', '位置在金家山社区西南门旁。'],
        mapKeyword: '徐军老汤店 金家山社区西南门旁 起凤路',
        amapName: '徐军老汤店',
        amapAddress: '南昌市东湖区金家山社区西南门旁(起凤路地铁站4号口步行490米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFGIDQCI&name=%E5%BE%90%E5%86%9B%E8%80%81%E6%B1%A4%E5%BA%97',
        amapPoiId: 'B0FFGIDQCI',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-12',
        no: 'D16',
        category: '夜宵类',
        shortName: '王辉鸭三宝',
        fullName: '王辉鸭三宝(五鑫大厦店)',
        dish: '鸭头、鸭翅、鸭三宝',
        address: '南昌市西湖区金盘路91号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['晚饭', '夜宵'],
        scenes: ['本地味道', '两三人一起', '晚点也能吃'],
        baseRating: 4.4,
        baseVotes: 10,
        seedNotes: ['想吃鸭货重口夜宵可以看它。', '两三个人点一些更合适。', '高德显示营业到夜里。'],
        mapKeyword: '王辉鸭三宝 五鑫大厦店 金盘路91号',
        amapName: '王辉鸭三宝(五鑫大厦店)',
        amapAddress: '南昌市西湖区金盘路91号(丁公路北地铁站7号口步行80米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0H30K8YGZ&name=%E7%8E%8B%E8%BE%89%E9%B8%AD%E4%B8%89%E5%AE%9D%28%E4%BA%94%E9%91%AB%E5%A4%A7%E5%8E%A6%E5%BA%97%29',
        amapPoiId: 'B0H30K8YGZ',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-13',
        no: 'D17',
        category: '夜宵类',
        shortName: '福旺财老鸭粉',
        fullName: '福旺财南京老鸭泡粉',
        dish: '老鸭泡粉',
        address: '南昌市西湖区船山路229号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['晚饭', '夜宵'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '晚点也能吃'],
        baseRating: 4.4,
        baseVotes: 327,
        seedNotes: ['晚上想吃粉汤类夜宵可以看它。', '一个人补一碗比较方便。', '船山路附近夜里可选。'],
        mapKeyword: '福旺财南京老鸭泡粉 船山路229号',
        amapName: '福旺财南京老鸭泡粉',
        amapAddress: '南昌市西湖区船山路229号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFFF9GPF&name=%E7%A6%8F%E6%97%BA%E8%B4%A2%E5%8D%97%E4%BA%AC%E8%80%81%E9%B8%AD%E6%B3%A1%E7%B2%89',
        amapPoiId: 'B0FFFF9GPF',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-14',
        no: 'C15',
        category: '中晚餐',
        shortName: '姐妹快餐',
        fullName: '姐妹快餐(建德观街)',
        dish: '红烧肉、快餐',
        address: '南昌市东湖区田家巷1号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 26,
        seedNotes: ['想快速吃顿家常快餐可以看它。', '一个人吃饭比较省事。', '适合午饭或晚饭不想纠结。'],
        mapKeyword: '姐妹快餐 建德观街 田家巷1号',
        amapName: '姐妹快餐(建德观街)',
        amapAddress: '南昌市东湖区田家巷1号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B03170S3Z4&name=%E5%A7%90%E5%A6%B9%E5%BF%AB%E9%A4%90%28%E5%BB%BA%E5%BE%B7%E8%A7%82%E8%A1%97%29',
        amapPoiId: 'B03170S3Z4',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-15',
        no: 'C16',
        category: '中晚餐',
        shortName: '羊子两室一厅',
        fullName: '羊子两室一厅',
        dish: '本地烧菜',
        address: '南昌市西湖区羊子街鸭子塘巷2号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起'],
        baseRating: 4.7,
        baseVotes: 298,
        seedNotes: ['想吃本地烧菜可以认真看这家。', '两三个人点菜更合适。', '街坊感会比较强。'],
        mapKeyword: '羊子两室一厅 羊子街鸭子塘巷2号',
        amapName: '羊子两室一厅',
        amapAddress: '南昌市西湖区羊子街鸭子塘巷2号(八一广场地铁站5号口步行460米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0317040GD&name=%E7%BE%8A%E5%AD%90%E4%B8%A4%E5%AE%A4%E4%B8%80%E5%8E%85',
        amapPoiId: 'B0317040GD',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-16',
        no: 'C17',
        category: '中晚餐',
        shortName: '佳佳麻辣烧菜',
        fullName: '佳佳麻辣烧菜馆',
        dish: '麻辣烧菜',
        address: '南昌市西湖区蓼洲街48号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起'],
        baseRating: 4.4,
        baseVotes: 132,
        seedNotes: ['想吃口味重一点的烧菜可以看它。', '适合两三个人一起去。', '万寿宫附近备选。'],
        mapKeyword: '佳佳麻辣烧菜馆 蓼洲街48号',
        amapName: '佳佳麻辣烧菜馆',
        amapAddress: '南昌市西湖区蓼洲街48号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0317061K0&name=%E4%BD%B3%E4%BD%B3%E9%BA%BB%E8%BE%A3%E7%83%A7%E8%8F%9C%E9%A6%86',
        amapPoiId: 'B0317061K0',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-02',
        no: 'A01',
        category: '早餐类',
        shortName: '高师傅米粉汤包',
        fullName: '高师傅特色米粉汤包(建设路店)',
        dish: '米粉、汤包',
        address: '南昌市青云谱区建设路276号1层',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃粉和汤包可以先看这家。', '适合早上快速吃饱。', '用户已确认建设路店。'],
        mapKeyword: '高师傅特色米粉汤包 建设路店 建设路276号',
        amapName: '高师傅特色米粉汤包(建设路店)',
        amapAddress: '南昌市青云谱区建设路276号1层',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B03170SZ7I&name=%E9%AB%98%E5%B8%88%E5%82%85%E7%89%B9%E8%89%B2%E7%B1%B3%E7%B2%89%E6%B1%A4%E5%8C%85%28%E5%BB%BA%E8%AE%BE%E8%B7%AF%E5%BA%97%29',
        amapPoiId: 'B03170SZ7I',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-03',
        no: 'A02',
        category: '早餐类',
        shortName: '老刘汤粉',
        fullName: '老刘汤粉店(月池路店)',
        dish: '汤粉',
        address: '南昌市西湖区月池路210号',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['近距离汤粉备选。', '早上不想走远可以看它。', '一个人吃很方便。'],
        mapKeyword: '老刘汤粉店 月池路店 月池路210号',
        amapName: '老刘汤粉店(月池路店)',
        amapAddress: '南昌市西湖区月池路210号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0HGF4479W&name=%E8%80%81%E5%88%98%E6%B1%A4%E7%B2%89%E5%BA%97(%E6%9C%88%E6%B1%A0%E8%B7%AF%E5%BA%97)',
        amapPoiId: 'B0HGF4479W',
        amapLocation: '115.883314,28.647592',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-04',
        no: 'A04',
        category: '早餐类',
        shortName: '超越猪血汤',
        fullName: '超越猪血汤炸酱面馆(桃苑店)',
        dish: '猪血汤、炸酱面',
        address: '南昌市西湖区朝阳领秀住宅小区1号楼东门旁',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['猪血汤和面食都能选。', '适合早餐或中午快速吃一顿。', '桃苑附近备选。'],
        mapKeyword: '超越猪血汤炸酱面馆 桃苑店 朝阳领秀',
        amapName: '超越猪血汤炸酱面馆(桃苑店)',
        amapAddress: '南昌市西湖区朝阳领秀住宅小区1号楼东门旁',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031705BBH&name=%E8%B6%85%E8%B6%8A%E7%8C%AA%E8%A1%80%E6%B1%A4%E7%82%B8%E9%85%B1%E9%9D%A2%E9%A6%86(%E6%A1%83%E8%8B%91%E5%BA%97)',
        amapPoiId: 'B031705BBH',
        amapLocation: '115.885185,28.665120',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-05',
        no: 'A05',
        category: '早餐类',
        shortName: '阿莲猪血粉',
        fullName: '阿莲猪血粉(桃园住宅区店)',
        dish: '猪血粉',
        address: '南昌市西湖区广厦社区18栋',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃猪血粉可以看这家。', '适合本地味早餐。', '离桃苑地铁站不远。'],
        mapKeyword: '阿莲猪血粉 桃园住宅区店 广厦社区18栋',
        amapName: '阿莲猪血粉(桃园住宅区店)',
        amapAddress: '南昌市西湖区广厦社区18栋(桃苑地铁站4号口步行250米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFFVRFE7&name=%E9%98%BF%E8%8E%B2%E7%8C%AA%E8%A1%80%E7%B2%89(%E6%A1%83%E5%9B%AD%E4%BD%8F%E5%AE%85%E5%8C%BA%E5%BA%97)',
        amapPoiId: 'B0FFFVRFE7',
        amapLocation: '115.888380,28.657968',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-06',
        no: 'A06',
        category: '早餐类',
        shortName: '百年老汤',
        fullName: '百年老汤(桃园住宅区店)',
        dish: '老汤、粉面',
        address: '南昌市西湖区桃苑大街328号东侧门',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想喝汤类早餐可以看它。', '粉面汤组合比较稳。', '桃园住宅区附近备选。'],
        mapKeyword: '百年老汤 桃园住宅区店 桃苑大街328号',
        amapName: '百年老汤(桃园住宅区店)',
        amapAddress: '南昌市西湖区桃苑大街328号东侧门(桃苑地铁站4号口步行410米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0G1P6G76H&name=%E7%99%BE%E5%B9%B4%E8%80%81%E6%B1%A4(%E6%A1%83%E5%9B%AD%E4%BD%8F%E5%AE%85%E5%8C%BA%E5%BA%97)',
        amapPoiId: 'B0G1P6G76H',
        amapLocation: '115.886988,28.658221',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-07',
        no: 'A07',
        category: '早餐类',
        shortName: '珊珊汤店',
        fullName: '珊珊汤店(永叔路店)',
        dish: '瓦罐汤、拌粉',
        address: '南昌市西湖区永叔路76号',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['汤粉类早餐备选。', '永叔路店为已确认目标店。', '一个人吃饭比较顺手。'],
        mapKeyword: '珊珊汤店 永叔路店 永叔路76号',
        amapName: '珊珊汤店(永叔路店)',
        amapAddress: '南昌市西湖区永叔路76号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031703X69&name=%E7%8F%8A%E7%8F%8A%E6%B1%A4%E5%BA%97(%E6%B0%B8%E5%8F%94%E8%B7%AF%E5%BA%97)',
        amapPoiId: 'B031703X69',
        amapLocation: '115.897346,28.664526',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-08',
        no: 'A08',
        category: '早餐类',
        shortName: '章氏汤包',
        fullName: '章氏汤包店(罗家塘路店)',
        dish: '汤包',
        address: '南昌市西湖区罗家塘路24号',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃汤包可以看它。', '早餐快速吃饱比较合适。', '罗家塘路店已确认。'],
        mapKeyword: '章氏汤包店 罗家塘路店 罗家塘路24号',
        amapName: '章氏汤包店(罗家塘路店)',
        amapAddress: '南昌市西湖区罗家塘路24号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B03170416U&name=%E7%AB%A0%E6%B0%8F%E6%B1%A4%E5%8C%85%E5%BA%97(%E7%BD%97%E5%AE%B6%E5%A1%98%E8%B7%AF%E5%BA%97)',
        amapPoiId: 'B03170416U',
        amapLocation: '115.901063,28.666924',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-09',
        no: 'A09',
        category: '早餐类',
        shortName: '天津包子王',
        fullName: '天津包子王(朝阳洲中路店)',
        dish: '包子',
        address: '南昌市西湖区朝阳洲中路35号',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '一个人方便', '便宜不踩雷'],
        baseRating: 4.4,
        baseVotes: 12,
        seedNotes: ['想买包子可以看这家。', '早上赶时间比较方便。', '朝阳洲中路店已确认。'],
        mapKeyword: '天津包子王 朝阳洲中路店 朝阳洲中路35号',
        amapName: '天津包子王(朝阳洲中路店)',
        amapAddress: '南昌市西湖区朝阳洲中路35号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031703Y5S&name=%E5%A4%A9%E6%B4%A5%E5%8C%85%E5%AD%90%E7%8E%8B(%E6%9C%9D%E9%98%B3%E6%B4%B2%E4%B8%AD%E8%B7%AF%E5%BA%97)',
        amapPoiId: 'B031703Y5S',
        amapLocation: '115.884454,28.664985',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-10',
        no: 'D01',
        category: '夜宵类',
        shortName: '三眼井烧烤',
        fullName: '三眼井特色烧烤总店(仕中心80公馆)',
        dish: '烧烤',
        address: '南昌市西湖区象山南路68号',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['晚饭', '夜宵'],
        scenes: ['本地味道', '两三人一起', '晚点也能吃'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃烧烤夜宵可以看它。', '两三个人一起更合适。', '仕中心80公馆店已确认。'],
        mapKeyword: '三眼井特色烧烤总店 仕中心80公馆 象山南路68号',
        amapName: '三眼井特色烧烤总店(仕中心80公馆)',
        amapAddress: '南昌市西湖区象山南路68号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFJ0B8MF&name=%E4%B8%89%E7%9C%BC%E4%BA%95%E7%89%B9%E8%89%B2%E7%83%A7%E7%83%A4%E6%80%BB%E5%BA%97(%E4%BB%95%E4%B8%AD%E5%BF%8380%E5%85%AC%E9%A6%86%20)',
        amapPoiId: 'B0FFJ0B8MF',
        amapLocation: '115.894986,28.664638',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-11',
        no: 'D02',
        category: '夜宵类',
        shortName: '田螺王',
        fullName: '田螺王(船山路店)',
        dish: '田螺、烧烤',
        address: '南昌市西湖区船山路217号',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['晚饭', '夜宵'],
        scenes: ['本地味道', '两三人一起', '晚点也能吃'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃田螺烧烤可以看它。', '夜宵结伴比较合适。', '船山路店已确认。'],
        mapKeyword: '田螺王 船山路店 船山路217号',
        amapName: '田螺王(船山路店)',
        amapAddress: '南昌市西湖区南浦街道船山路217号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B03170SU5E&name=%E7%94%B0%E8%9E%BA%E7%8E%8B(%E8%88%B9%E5%B1%B1%E8%B7%AF%E5%BA%97)',
        amapPoiId: 'B03170SU5E',
        amapLocation: '115.891929,28.666348',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-12',
        no: 'C01',
        category: '中晚餐',
        shortName: '南浦两室一厅',
        fullName: '南浦两室一厅(南浦路店)',
        dish: '南昌烧菜',
        address: '南昌市西湖区濠上街社区',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃南昌烧菜可以看这家。', '两三个人点菜更合适。', '南浦路店已确认。'],
        mapKeyword: '南浦两室一厅 南浦路店 濠上街社区',
        amapName: '南浦两室一厅(南浦路店)',
        amapAddress: '南昌市西湖区濠上街社区(六眼井地铁站3号口步行460米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0IATGI68P&name=%E5%8D%97%E6%B5%A6%E4%B8%A4%E5%AE%A4%E4%B8%80%E5%8E%85(%E5%8D%97%E6%B5%A6%E8%B7%AF%E5%BA%97)',
        amapPoiId: 'B0IATGI68P',
        amapLocation: '115.889738,28.667677',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-13',
        no: 'C02',
        category: '中晚餐',
        shortName: '宏纪源赣南菜',
        fullName: '宏纪源赣南菜馆(抚河园小区店)',
        dish: '赣南菜',
        address: '南昌市西湖区桃苑二区17栋A号',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃赣南菜可以看它。', '适合两三人一起点菜。', '抚河园小区店已确认。'],
        mapKeyword: '宏纪源赣南菜馆 抚河园小区店 桃苑二区17栋A号',
        amapName: '宏纪源赣南菜馆(抚河园小区店)',
        amapAddress: '南昌市西湖区桃苑二区17栋A号(桃苑地铁站3号口步行290米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B03170SW08&name=%E5%AE%8F%E7%BA%AA%E6%BA%90%E8%B5%A3%E5%8D%97%E8%8F%9C%E9%A6%86(%E6%8A%9A%E6%B2%B3%E5%9B%AD%E5%B0%8F%E5%8C%BA%E5%BA%97)',
        amapPoiId: 'B03170SW08',
        amapLocation: '115.890418,28.662036',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-14',
        no: 'C03',
        category: '中晚餐',
        shortName: '农家腊味馆',
        fullName: '农家腊味馆(船山路)',
        dish: '腊味、烧菜',
        address: '南昌市西湖区船山路402号',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃腊味烧菜可以看它。', '适合两三个人一起去。', '船山路店已确认。'],
        mapKeyword: '农家腊味馆 船山路 船山路402号',
        amapName: '农家腊味馆(船山路)',
        amapAddress: '南昌市西湖区船山路与南浦路交接船山路402号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B031705BV1&name=%E5%86%9C%E5%AE%B6%E8%85%8A%E5%91%B3%E9%A6%86(%E8%88%B9%E5%B1%B1%E8%B7%AF)',
        amapPoiId: 'B031705BV1',
        amapLocation: '115.890169,28.668482',
        verificationStatus: 'verified',
    },
    {
        id: 'R05-15',
        no: 'C04',
        category: '中晚餐',
        shortName: '小黄鱼滋味馆',
        fullName: '小黄鱼滋味馆(赣通路店)',
        dish: '小黄鱼、烧菜',
        address: '南昌市西湖区桃园住宅区西南门北210米',
        rideMinutes: 5,
        rideBand: '骑行 5 分钟内',
        sourceBand: '骑行 5 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃鱼类烧菜可以看它。', '两三个人点菜更合适。', '赣通路店已确认。'],
        mapKeyword: '小黄鱼滋味馆 赣通路店 桃园住宅区西南门',
        amapName: '小黄鱼滋味馆(赣通路店)',
        amapAddress: '南昌市西湖区桃园住宅区西南门北210米',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0FFFF5IA6&name=%E5%B0%8F%E9%BB%84%E9%B1%BC%E6%BB%8B%E5%91%B3%E9%A6%86(%E8%B5%A3%E9%80%9A%E8%B7%AF%E5%BA%97)',
        amapPoiId: 'B0FFFF5IA6',
        amapLocation: '115.886961,28.658978',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-08',
        no: 'A12',
        category: '早餐类',
        shortName: '月月红汤粉',
        fullName: '月月红汤粉店(京山北路店)',
        dish: '汤粉',
        address: '南昌市青云谱区京山北路通用机械厂',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['汤粉类早餐备选。', '适合早上快速吃饱。', '京山北路店已确认。'],
        mapKeyword: '月月红汤粉店 京山北路店 京山北路通用机械厂',
        amapName: '月月红汤粉店(京山北路店)',
        amapAddress: '南昌市青云谱区京山街道京山北路通用机械厂',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?id=B0H6YS7GQV&name=%E6%9C%88%E6%9C%88%E7%BA%A2%E6%B1%A4%E7%B2%89%E5%BA%97(%E4%BA%AC%E5%B1%B1%E5%8C%97%E8%B7%AF%E5%BA%97)',
        amapPoiId: 'B0H6YS7GQV',
        amapLocation: '115.906223,28.646824',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-09',
        no: 'A21',
        category: '早餐类',
        shortName: '周记生煎',
        fullName: '周记生煎(船山店)',
        dish: '生煎',
        address: '船山路402号(六眼井地铁站3号口步行370米)',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['早餐', '午饭', '下午加餐'],
        scenes: ['快点吃饱', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃热乎生煎可以看这家。', '早餐或下午垫一口都方便。', '离窝窝不算远，适合轻松骑过去。'],
        mapKeyword: '周记生煎 船山路402号 南昌',
        amapName: '周记生煎(船山店)',
        amapAddress: '船山路402号(六眼井地铁站3号口步行370米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E5%91%A8%E8%AE%B0%E7%94%9F%E7%85%8E+%E8%88%B9%E5%B1%B1%E8%B7%AF402%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0G1FHLMAH&source=ai_search_result',
        amapPoiId: 'B0G1FHLMAH',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-10',
        no: 'D21',
        category: '夜宵类',
        shortName: '峡江佬烧烤',
        fullName: '峡江佬烧烤(裘家厂住宅区店)',
        dish: '烧烤',
        address: '胜利路裘家厂社区10栋',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['晚饭', '夜宵'],
        scenes: ['两三人一起', '晚点也能吃', '本地味道'],
        baseRating: 4.4,
        baseVotes: 11,
        seedNotes: ['晚上想吃热闹点可以看它。', '适合两三个人一起去。', '烧烤局别忘了先看高德。'],
        mapKeyword: '峡江佬烧烤 胜利路裘家厂社区10栋 南昌',
        amapName: '峡江佬烧烤(裘家厂住宅区店)',
        amapAddress: '胜利路裘家厂社区10栋',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E5%B3%A1%E6%B1%9F%E4%BD%AC%E7%83%A7%E7%83%A4+%E8%83%9C%E5%88%A9%E8%B7%AF%E8%A3%98%E5%AE%B6%E5%8E%82%E7%A4%BE%E5%8C%BA10%E6%A0%8B+%E5%8D%97%E6%98%8C&city=360100&id=B0H2RA3XCH&source=ai_search_result&name=%E5%B3%A1%E6%B1%9F%E4%BD%AC%E7%83%A7%E7%83%A4%28%E8%A3%98%E5%AE%B6%E5%8E%82%E4%BD%8F%E5%AE%85%E5%8C%BA%E5%BA%97%29',
        amapPoiId: 'B0H2RA3XCH',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-11',
        no: 'D22',
        category: '夜宵类',
        shortName: '思烤家鹤岗小串',
        fullName: '思烤家鹤岗小串滋(桃花路店)',
        dish: '鹤岗小串',
        address: '朝阳洲象抚路滕王阁花园小区桃花中路振中小区8栋15号',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['晚饭', '夜宵'],
        scenes: ['两三人一起', '晚点也能吃'],
        baseRating: 4.3,
        baseVotes: 10,
        seedNotes: ['小串类更适合晚上去。', '朋友结伴时可以放进备选。', '想吃点有烟火气的可以看这家。'],
        mapKeyword: '思烤家鹤岗小串 桃花中路振中小区8栋15号 南昌',
        amapName: '思烤家鹤岗小串滋(桃花路店)',
        amapAddress: '朝阳洲象抚路滕王阁花园小区桃花中路振中小区8栋15号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E6%80%9D%E7%83%A4%E5%AE%B6%E9%B9%A4%E5%B2%97%E5%B0%8F%E4%B8%B2+%E6%A1%83%E8%8A%B1%E4%B8%AD%E8%B7%AF%E6%8C%AF%E4%B8%AD%E5%B0%8F%E5%8C%BA8%E6%A0%8B15%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0J2RCWLKF&source=ai_search_result',
        amapPoiId: 'B0J2RCWLKF',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-12',
        no: 'C21',
        category: '中晚餐',
        shortName: '文武酒家',
        fullName: '文武酒家(付家坡小区店)',
        dish: '家常菜',
        address: '付家坡小区西门旁(八一馆地铁站1号口步行460米)',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 13,
        seedNotes: ['适合正经吃顿家常菜。', '两三个人点菜会更舒服。', '想吃饭不想太复杂可以看它。'],
        mapKeyword: '文武酒家 付家坡小区西门旁 南昌',
        amapName: '文武酒家(付家坡小区店)',
        amapAddress: '付家坡小区西门旁(八一馆地铁站1号口步行460米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E6%96%87%E6%AD%A6%E9%85%92%E5%AE%B6+%E4%BB%98%E5%AE%B6%E5%9D%A1%E5%B0%8F%E5%8C%BA%E8%A5%BF%E9%97%A8%E6%97%81+%E5%8D%97%E6%98%8C&city=360100&id=B03170STO0&source=ai_search_result&name=%E6%96%87%E6%AD%A6%E9%85%92%E5%AE%B6%28%E4%BB%98%E5%AE%B6%E5%9D%A1%E5%B0%8F%E5%8C%BA%E5%BA%97%29',
        amapPoiId: 'B03170STO0',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-13',
        no: 'C22',
        category: '中晚餐',
        shortName: '英子家庭菜馆',
        fullName: '英子家庭菜馆',
        dish: '家常菜',
        address: '系马桩306号黄秋园纪念馆斜对面',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起', '便宜不踩雷'],
        baseRating: 4.4,
        baseVotes: 11,
        seedNotes: ['家庭菜馆适合吃一顿热饭。', '两三人一起点菜更合适。', '想找本地小馆可以看这家。'],
        mapKeyword: '英子家庭菜馆 系马桩306号 南昌',
        amapName: '英子家庭菜馆',
        amapAddress: '系马桩306号黄秋园纪念馆斜对面',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E8%8B%B1%E5%AD%90%E5%AE%B6%E5%BA%AD%E8%8F%9C%E9%A6%86+%E7%B3%BB%E9%A9%AC%E6%A1%A9306%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B031703JHA&source=ai_search_result',
        amapPoiId: 'B031703JHA',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-14',
        no: 'C23',
        category: '中晚餐',
        shortName: '顺记菜馆',
        fullName: '顺记菜馆',
        dish: '家常菜',
        address: '儒子路202号(六眼井地铁站1号口步行260米)',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['午饭', '晚饭'],
        scenes: ['本地味道', '两三人一起', '便宜不踩雷'],
        baseRating: 4.4,
        baseVotes: 10,
        seedNotes: ['想吃小馆炒菜可以看它。', '适合午饭或晚饭。', '两三人一起去更容易点菜。'],
        mapKeyword: '顺记菜馆 儒子路202号 南昌',
        amapName: '顺记菜馆',
        amapAddress: '儒子路202号(六眼井地铁站1号口步行260米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E9%A1%BA%E8%AE%B0%E8%8F%9C%E9%A6%86+%E5%84%92%E5%AD%90%E8%B7%AF202%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0IATYIMP8&source=ai_search_result&name=%E9%A1%BA%E8%AE%B0%E8%8F%9C%E9%A6%86',
        amapPoiId: 'B0IATYIMP8',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-15',
        no: 'C24',
        category: '中晚餐',
        shortName: '饶记牛魔王',
        fullName: '饶记牛魔王辣味馆(船山路总店)',
        dish: '辣味牛肉',
        address: '船山路与禾草街交叉口西北100米',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['午饭', '晚饭', '夜宵'],
        scenes: ['本地味道', '两三人一起', '晚点也能吃'],
        baseRating: 4.6,
        baseVotes: 16,
        seedNotes: ['能吃辣的话可以优先看这家。', '适合晚饭吃得重口一点。', '两三个人一起更好点菜。'],
        mapKeyword: '饶记牛魔王辣味馆 船山路 禾草街 南昌',
        amapName: '饶记牛魔王辣味馆(船山路总店)',
        amapAddress: '船山路与禾草街交叉口西北100米',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E9%A5%B6%E8%AE%B0%E7%89%9B%E9%AD%94%E7%8E%8B%E8%BE%A3%E5%91%B3%E9%A6%86+%E8%88%B9%E5%B1%B1%E8%B7%AF+%E7%A6%BE%E8%8D%89%E8%A1%97+%E5%8D%97%E6%98%8C&city=360100&id=B0JDGUUIOH&source=ai_search_result&name=%E9%A5%B6%E8%AE%B0%E7%89%9B%E9%AD%94%E7%8E%8B%E8%BE%A3%E5%91%B3%E9%A6%86%28%E8%88%B9%E5%B1%B1%E8%B7%AF%E6%80%BB%E5%BA%97%29',
        amapPoiId: 'B0JDGUUIOH',
        verificationStatus: 'verified',
    },
    {
        id: 'R10-16',
        no: 'B21',
        category: '小吃类',
        shortName: '邓伙妹臭豆腐',
        fullName: '邓伙妹臭豆腐(老字号南浦路24中对面店)',
        dish: '臭豆腐',
        address: '南浦路108号',
        rideMinutes: 10,
        rideBand: '骑行 10 分钟内',
        sourceBand: '骑行 10 分钟内',
        times: ['下午加餐', '晚饭', '夜宵'],
        scenes: ['本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.6,
        baseVotes: 17,
        seedNotes: ['想吃南昌小吃可以看这家。', '一个人加餐也方便。', '臭豆腐爱好者可以放进收藏。'],
        mapKeyword: '邓伙妹臭豆腐 南浦路108号 南昌',
        amapName: '邓伙妹臭豆腐(老字号南浦路24中对面店)',
        amapAddress: '南浦路108号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E9%82%93%E4%BC%99%E5%A6%B9%E8%87%AD%E8%B1%86%E8%85%90+%E5%8D%97%E6%B5%A6%E8%B7%AF108%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0G35SU3VF&source=ai_search_result&name=%E9%82%93%E4%BC%99%E5%A6%B9%E8%87%AD%E8%B1%86%E8%85%90%28%E8%80%81%E5%AD%97%E5%8F%B7%E5%8D%97%E6%B5%A6%E8%B7%AF24%E4%B8%AD%E5%AF%B9%E9%9D%A2%E5%BA%97%29',
        amapPoiId: 'B0G35SU3VF',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-17',
        no: 'A22',
        category: '早餐类',
        shortName: '恒茂汤店',
        fullName: '恒茂汤店(恒茂国际华城商业街店)',
        dish: '汤粉',
        address: '丁公路98号恒茂国际华城商业街',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.3,
        baseVotes: 9,
        seedNotes: ['早餐想喝汤吃粉可以看它。', '一个人去也比较方便。', '骑得稍远一点换个口味。'],
        mapKeyword: '恒茂汤店 丁公路98号 南昌',
        amapName: '恒茂汤店(恒茂国际华城商业街店)',
        amapAddress: '丁公路98号恒茂国际华城商业街',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E6%81%92%E8%8C%82%E6%B1%A4%E5%BA%97+%E4%B8%81%E5%85%AC%E8%B7%AF98%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0317057ZQ&source=ai_search_result&name=%E6%81%92%E8%8C%82%E6%B1%A4%E5%BA%97%28%E6%81%92%E8%8C%82%E5%9B%BD%E9%99%85%E5%8D%8E%E5%9F%8E%E5%95%86%E4%B8%9A%E8%A1%97%E5%BA%97%29',
        amapPoiId: 'B0317057ZQ',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-18',
        no: 'A23',
        category: '早餐类',
        shortName: '浪琴汤店',
        fullName: '浪琴汤店',
        dish: '汤粉',
        address: '下水路74号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '午饭'],
        scenes: ['快点吃饱', '本地味道', '一个人方便', '便宜不踩雷'],
        baseRating: 4.4,
        baseVotes: 10,
        seedNotes: ['想吃本地汤粉可以看这家。', '早餐或午饭都能接上。', '适合一个人快速解决。'],
        mapKeyword: '浪琴汤店 下水路74号 南昌',
        amapName: '浪琴汤店',
        amapAddress: '下水路74号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E6%B5%AA%E7%90%B4%E6%B1%A4%E5%BA%97+%E4%B8%8B%E6%B0%B4%E8%B7%AF74%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0KR7CKWV7&source=ai_search_result&name=%E6%B5%AA%E7%90%B4%E6%B1%A4%E5%BA%97',
        amapPoiId: 'B0KR7CKWV7',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-19',
        no: 'B22',
        category: '小吃类',
        shortName: '小平夫妻粽子',
        fullName: '小平夫妻粽子(新世纪住宅小区店)',
        dish: '粽子',
        address: '棉花街10号(八一馆地铁站5号口步行240米)',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '下午加餐'],
        scenes: ['快点吃饱', '一个人方便', '便宜不踩雷'],
        baseRating: 4.5,
        baseVotes: 12,
        seedNotes: ['想吃点简单垫肚子可以看它。', '早餐和下午加餐都适合。', '粽子类比较好带走。'],
        mapKeyword: '小平夫妻粽子 棉花街10号 南昌',
        amapName: '小平夫妻粽子(新世纪住宅小区店)',
        amapAddress: '棉花街10号(八一馆地铁站5号口步行240米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E5%B0%8F%E5%B9%B3%E5%A4%AB%E5%A6%BB%E7%B2%BD%E5%AD%90+%E6%A3%89%E8%8A%B1%E8%A1%9710%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0IBO5I4SK&source=ai_search_result&name=%E5%B0%8F%E5%B9%B3%E5%A4%AB%E5%A6%BB%E7%B2%BD%E5%AD%90%28%E6%96%B0%E4%B8%96%E7%BA%AA%E4%BD%8F%E5%AE%85%E5%B0%8F%E5%8C%BA%E5%BA%97%29',
        amapPoiId: 'B0IBO5I4SK',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-20',
        no: 'B23',
        category: '小吃类',
        shortName: '小吴水煮',
        fullName: '小吴水煮',
        dish: '水煮',
        address: '羊子街84号(八一广场地铁站5号口步行390米)',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['下午加餐', '晚饭', '夜宵'],
        scenes: ['本地味道', '一个人方便', '晚点也能吃'],
        baseRating: 4.4,
        baseVotes: 11,
        seedNotes: ['想吃水煮小吃可以看这家。', '夜里回来加餐也能考虑。', '同名店多，高德已绑羊子街84号。'],
        mapKeyword: '小吴水煮 羊子街84号 南昌',
        amapName: '小吴水煮',
        amapAddress: '羊子街84号(八一广场地铁站5号口步行390米)',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E5%B0%8F%E5%90%B4%E6%B0%B4%E7%85%AE+%E7%BE%8A%E5%AD%90%E8%A1%9784%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0FFHU9W1W&source=ai_search_result',
        amapPoiId: 'B0FFHU9W1W',
        verificationStatus: 'verified',
    },
    {
        id: 'R15-21',
        no: 'B24',
        category: '小吃类',
        shortName: '天天大饼',
        fullName: '天天大饼',
        dish: '大饼',
        address: '广润门街道象山南路312号',
        rideMinutes: 15,
        rideBand: '骑行 15 分钟内',
        sourceBand: '骑行 15 分钟内',
        times: ['早餐', '下午加餐'],
        scenes: ['快点吃饱', '一个人方便', '便宜不踩雷'],
        baseRating: 4.3,
        baseVotes: 9,
        seedNotes: ['想吃简单主食可以看它。', '适合早餐或下午垫一下。', '不用想太多的一口碳水。'],
        mapKeyword: '天天大饼 象山南路312号 南昌',
        amapName: '天天大饼',
        amapAddress: '广润门街道象山南路312号',
        amapLink:
            'https://www.amap.com/ssr/search/poi_detail?query_type=TQUERY&query=%E5%A4%A9%E5%A4%A9%E5%A4%A7%E9%A5%BC+%E8%B1%A1%E5%B1%B1%E5%8D%97%E8%B7%AF312%E5%8F%B7+%E5%8D%97%E6%98%8C&city=360100&id=B0FFHS295C&source=ai_search_result&name=%E5%A4%A9%E5%A4%A9%E5%A4%A7%E9%A5%BC',
        amapPoiId: 'B0FFHS295C',
        verificationStatus: 'verified',
    },
];

export const verifiedRestaurants = wowoRestaurants.filter(
    (restaurant) =>
        restaurant.verificationStatus === 'verified' &&
        restaurant.amapAddress &&
        (restaurant.amapPoiId || restaurant.amapLocation)
);

const resolvedPendingNames = new Set([
    '高师傅特色米粉汤包',
    '老刘汤粉店（月池路）',
    '超越猪血汤炸酱面馆',
    '阿莲猪血粉',
    '百年老汤',
    '珊珊汤店',
    '章氏汤包店',
    '天津包子王',
    '三眼井特色烧烤',
    '田螺王烧烤',
    '南浦两室一厅',
    '宏纪源赣南菜馆',
    '农家腊味馆',
    '小黄鱼滋味馆',
    '月月红汤粉店',
    '良友小吃',
    '英姐小吃',
    '鄱湖岛饭庄',
    '黄记瓦罐汤',
    '胖子水煮店',
    '小敖臭豆腐',
    '老字号眼镜子煎包汤包店',
    '眼镜子生煎',
    '夫妻切糕店',
    '徐军老汤店',
    '王辉鸭三宝',
    '福旺财南京老鸭泡粉',
    '姐妹快餐',
    '羊子两室一厅',
    '佳佳麻辣烧菜馆',
    '周记生煎',
    '峡江佬烧烤',
    '思烤家鹤岗小串',
    '文武酒家',
    '英子家庭菜馆',
    '顺记菜馆',
    '饶记牛魔王辣味馆',
    '邓伙妹臭豆腐',
    '恒茂汤店',
    '浪琴汤店',
    '小平夫妻粽子',
    '小吴水煮',
    '天天大饼',
    '大树下饭店',
    '南翔包子店',
]);

export const pendingAmapRestaurants: PendingAmapRestaurant[] = (
    [
        {
            name: '高师傅特色米粉汤包',
            sourceBand: '骑行 5 分钟内',
            category: '早餐类',
            reason: '高德可查到相近“高师傅汤粉店”，但与文档店名不完全一致，需确认是否同一家。',
            suggestedKeyword: '高师傅特色米粉汤包 南昌',
        },
        {
            name: '老刘汤粉店（月池路）',
            sourceBand: '骑行 5 分钟内',
            category: '早餐类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '老刘汤粉店 月池路 南昌',
        },
        {
            name: '超越猪血汤炸酱面馆',
            sourceBand: '骑行 5 分钟内',
            category: '早餐类',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '超越猪血汤炸酱面馆 桃苑店',
        },
        {
            name: '阿莲猪血粉',
            sourceBand: '骑行 5 分钟内',
            category: '早餐类',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '阿莲猪血粉丝 桃园住宅区店',
        },
        {
            name: '百年老汤',
            sourceBand: '骑行 5 分钟内',
            category: '早餐类',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '百年老汤 桃园住宅区店',
        },
        {
            name: '珊珊汤店',
            sourceBand: '骑行 5 分钟内',
            category: '早餐类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '珊珊汤店 南昌',
        },
        {
            name: '章氏汤包店',
            sourceBand: '骑行 5 分钟内',
            category: '早餐类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '章氏汤包店 南昌',
        },
        {
            name: '天津包子王',
            sourceBand: '骑行 5 分钟内',
            category: '早餐类',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '天津包子王 朝阳洲中路店',
        },
        {
            name: '三眼井特色烧烤',
            sourceBand: '骑行 5 分钟内',
            category: '夜宵类',
            reason: '多门店/门牌线索不稳定，需确认目标店。',
            suggestedKeyword: '三眼井特色烧烤 仕中心80公馆店',
        },
        {
            name: '田螺王烧烤',
            sourceBand: '骑行 5 分钟内',
            category: '夜宵类',
            reason: '“船山店”和老牌总店线索冲突，需确认目标店。',
            suggestedKeyword: '田螺王 船山店 南昌',
        },
        {
            name: '南浦两室一厅',
            sourceBand: '骑行 5 分钟内',
            category: '中晚餐',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '南浦两室一厅 南浦路店',
        },
        {
            name: '宏纪源赣南菜馆',
            sourceBand: '骑行 5 分钟内',
            category: '中晚餐',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '宏纪源赣南菜馆 抚河园小区店',
        },
        {
            name: '农家腊味馆',
            sourceBand: '骑行 5 分钟内',
            category: '中晚餐',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '农家腊味馆 船山路店',
        },
        {
            name: '小黄鱼滋味馆',
            sourceBand: '骑行 5 分钟内',
            category: '中晚餐',
            reason: '门牌线索不稳定，需确认目标店。',
            suggestedKeyword: '小黄鱼滋味馆 赣通路店',
        },
        {
            name: '月月红汤粉店',
            sourceBand: '骑行 10 分钟内',
            category: '早餐类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '月月红汤粉店 南昌',
        },
        {
            name: '良友小吃',
            sourceBand: '骑行 10 分钟内',
            category: '早餐类',
            reason: '店名泛化，重名风险高。',
            suggestedKeyword: '良友小吃 小笼包 南昌',
        },
        {
            name: '周记生煎',
            sourceBand: '骑行 10 分钟内',
            category: '早餐类',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '周记生煎 船山店',
        },
        {
            name: '峡江佬烧烤',
            sourceBand: '骑行 10 分钟内',
            category: '夜宵类',
            reason: '目标分店/门牌未确认。',
            suggestedKeyword: '峡江佬烧烤 裘家场住宅区店',
        },
        {
            name: '英姐小吃',
            sourceBand: '骑行 10 分钟内',
            category: '夜宵类',
            reason: '店名泛化，重名风险高。',
            suggestedKeyword: '英姐小吃 水煮 南昌',
        },
        {
            name: '思烤家鹤岗小串',
            sourceBand: '骑行 10 分钟内',
            category: '夜宵类',
            reason: '桃花路店/桃苑路店名称线索冲突，需确认。',
            suggestedKeyword: '思烤家鹤岗小串 桃花路店',
        },
        {
            name: '文武酒家',
            sourceBand: '骑行 10 分钟内',
            category: '中晚餐',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '文武酒家 南昌',
        },
        {
            name: '大树下饭店',
            sourceBand: '骑行 10 分钟内',
            category: '中晚餐',
            reason: '店名泛化，重名风险高。',
            suggestedKeyword: '大树下饭店 南昌',
        },
        {
            name: '英子家庭菜馆',
            sourceBand: '骑行 10 分钟内',
            category: '中晚餐',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '英子家庭菜馆 南昌',
        },
        {
            name: '顺记菜馆',
            sourceBand: '骑行 10 分钟内',
            category: '中晚餐',
            reason: '店名泛化，重名风险高。',
            suggestedKeyword: '顺记菜馆 南昌',
        },
        {
            name: '饶记牛魔王辣味馆',
            sourceBand: '骑行 10 分钟内',
            category: '中晚餐',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '饶记牛魔王辣味馆 南昌',
        },
        {
            name: '鄱湖岛饭庄',
            sourceBand: '骑行 10 分钟内',
            category: '中晚餐',
            reason: '未取得稳定高德 POI/坐标；且文档标注价格偏高，需确认是否上线。',
            suggestedKeyword: '鄱湖岛饭庄 南昌',
        },
        {
            name: '邓伙妹臭豆腐',
            sourceBand: '骑行 10 分钟内',
            category: '下午加餐',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '邓伙妹臭豆腐 南浦路24中对面店',
        },
        {
            name: '黄记瓦罐汤',
            sourceBand: '骑行 15 分钟内',
            category: '早餐类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '黄记瓦罐汤 广场东路',
        },
        {
            name: '恒茂汤店',
            sourceBand: '骑行 15 分钟内',
            category: '早餐类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '恒茂汤店 广场东路',
        },
        {
            name: '浪琴汤店',
            sourceBand: '骑行 15 分钟内',
            category: '早餐类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '浪琴汤店 南昌',
        },
        {
            name: '南翔包子店',
            sourceBand: '骑行 15 分钟内',
            category: '早餐类',
            reason: '店名泛化，重名风险高。',
            suggestedKeyword: '南翔包子店 小笼包 南昌',
        },
        {
            name: '老字号眼镜子煎包汤包店',
            sourceBand: '骑行 15 分钟内',
            category: '早餐类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '老字号眼镜子煎包汤包店 南昌',
        },
        {
            name: '小平夫妻粽子',
            sourceBand: '骑行 15 分钟内',
            category: '下午加餐',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '小平夫妻粽子 南昌',
        },
        {
            name: '胖子水煮店',
            sourceBand: '骑行 15 分钟内',
            category: '下午加餐',
            reason: '重名/区域线索不稳定。',
            suggestedKeyword: '胖子水煮店 南昌',
        },
        {
            name: '小吴水煮',
            sourceBand: '骑行 15 分钟内',
            category: '下午加餐',
            reason: '店名泛化，重名风险高。',
            suggestedKeyword: '小吴水煮 南昌',
        },
        {
            name: '小敖臭豆腐',
            sourceBand: '骑行 15 分钟内',
            category: '下午加餐',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '小敖臭豆腐 南昌',
        },
        {
            name: '眼镜子生煎',
            sourceBand: '骑行 15 分钟内',
            category: '下午加餐',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '眼镜子生煎 南昌',
        },
        {
            name: '天天大饼',
            sourceBand: '骑行 15 分钟内',
            category: '下午加餐',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '天天大饼 象山南路312号',
        },
        {
            name: '夫妻切糕店',
            sourceBand: '骑行 15 分钟内',
            category: '下午加餐',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '缘夫妻切糕店 西上谕亭街14号',
        },
        {
            name: '徐军老汤店',
            sourceBand: '骑行 15 分钟内',
            category: '夜宵类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '徐军老汤店 南昌',
        },
        {
            name: '王辉鸭三宝',
            sourceBand: '骑行 15 分钟内',
            category: '夜宵类',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '王辉鸭三宝 南昌',
        },
        {
            name: '福旺财南京老鸭泡粉',
            sourceBand: '骑行 15 分钟内',
            category: '夜宵类',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '福旺财南京老鸭泡粉 船山路店',
        },
        {
            name: '姐妹快餐',
            sourceBand: '骑行 15 分钟内',
            category: '中晚餐',
            reason: '店名泛化，重名风险高。',
            suggestedKeyword: '姐妹快餐 红烧肉 南昌',
        },
        {
            name: '羊子两室一厅',
            sourceBand: '骑行 15 分钟内',
            category: '中晚餐',
            reason: '未取得稳定高德 POI/坐标。',
            suggestedKeyword: '羊子两室一厅 南昌',
        },
        {
            name: '佳佳麻辣烧菜馆',
            sourceBand: '骑行 15 分钟内',
            category: '中晚餐',
            reason: '当前只保留旧地址线索，未取得稳定高德 POI/坐标。',
            suggestedKeyword: '佳佳麻辣烧菜馆 蓼洲街店',
        },
    ] satisfies PendingAmapRestaurant[]
).filter((restaurant) => !resolvedPendingNames.has(restaurant.name));

export const seedNotes: WowoSeedNote[] = [
    {
        id: 'seed-1',
        shopName: '小邓臭豆腐',
        text: '适合刚到南昌先吃一口本地小吃。',
        createdAt: 1,
    },
    {
        id: 'seed-2',
        shopName: '小罗子汤店',
        text: '骑远一点去大士院吃粉汤也可以。',
        createdAt: 2,
    },
    {
        id: 'seed-3',
        shopName: '秦胖子肉陀',
        text: '早餐不想纠结可以看粉面汤。',
        createdAt: 3,
    },
];
